version: "3.7"
services:
  jenkins:
    build: .
    ports:
      - 8080:5000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      local-network:

  app:
    container_name: app
    build:
      context: ./app
    ports:
      - 5008:5000
    networks:
      local-network:

networks:
  local-network:
    external: false