# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r app/requirements.txt
      # Step 3: build
      - run:
          name: flask
          command: |
            . venv/bin/activate
            docker-compose up -d --build flask-app
      # Step 3: run tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest app/tests